title: cmp0x5
description: Reverse Engineering/Cryptography
theme: jekyll-theme-hacker
show_downloads: false
avatar: "/assets/images/favicon.ico"

social-network-links:
  rss: false
  github: cmp0x5
  twitter: cmp0x5
