title: cmp0x5
description: Blog and user page
theme: jekyll-theme-hacker
avatar: "/assets/images/favicon.ico"

social-network-links:
  rss: false
  email: "cmp0xf1@gmail.com"
  github: cmp0x5
  twitter: cmp0x5